### ISSUE TITLE
How do you keep glibc versions in sync

### ISSUE THREAD

**Issue by Mic92** [antithesishq/madness#1]
I wonder how do you make sure that LD_LIBRARY_PATH and the ld.so version are kept in sync.
i.e. if someone exports LD_LIBRARY_PATH in a devshell, how do you make sure that ld.so is of the same glibc version? Mixing versions will lead to crashes.

**Comment by wwilson** [comment]
Yes, this is a very annoying problem. There are two cases:

(1) The binary you're running was built with Nix, and you are trying to make it run on both NixOS and on other Linux systems. In this case, the binary will have the store path of the glibc version it was built against in the DT_RPATH header. So we just read it out of there, and use that version of ld.so. Since entries in DT_RPATH take precedence over all other dynamic resolution methods, we are guaranteed to get a matching glibc.

(2) The binary you're running was built on a different Linux, and has no references to the Nix store at all. In this case we just look at what glibc it *would* end up getting in the current environment (whether via LD_LIBRARY_PATH, or some other mechanism), and pick the matching ld.so.

As it happens, this initial open source release is still in progress, and we haven't uploaded the code for doing (2) yet. But it's actually quite simple. Case (1) is the tricky one, and it's the one that's most important for us, because we're building binaries on NixOS and then distributing them to the rest of the world.

**Comment by Mic92** [comment]
So you are just moving glibc to LD_LIBRARY_PATH?

**Comment by wwilson** [comment]
Not quite. Suppose you download a binary from the internet. It needs to be able to find its dynamic dependencies. We are not going to help you do that. Something like nix-shell is probably what you want to use. But if it *is* able to start, then that means it was able to find a copy of glibc. We will guarantee that you get a version of ld.so which matches that glibc. Is that clearer?
